# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 291d0e563bdeec911dd4ed69e945ab4cd6969c1b26353c23b3909ea0ed5192fba507d7e00d65f5a803ae1a338c8e5854c36a6e2a4eb163ca36e0a93987a3b639

test:
  secret_key_base: 49588a2d92560d98ebef5dec1e1f61032c2941375e0259786c1b7a1eac5c09dae3afbe7ee35823abef25f4f6448873909900d2d70012fcb5eae66bd958f60fbc

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
